class_name GameController
extends Node2D
## Responsible for running the game
##
## Handles user input, manages ball generation and game state

@export var game_over_timer: Timer ## [Timer] for game over countdown
@export var game_over_label: Label ## [Label] for game over text

@export var ball_top_offset: int = 400 ## height (from top) of the ball before dropping
@onready var ball_scene = preload("res://components/base-ball.tscn") ## Base ball scene (level 0)
var ball: Ball ## New ball currently being controlled by player

var game_ending: bool = false ## indicates whether there is a ball in ContainerTopArea
var game_over: bool = false ## indicates whether the game has ended

var should_drop: bool = false ## indicates whether the player has pressed a button to drop ball

@export var ball_min_x: int = 200 ## min global_position.x new ball will move to
@export var ball_max_x: int = 880 ## max global_position.x new ball will move to

func _ready():
	ReadyBall()

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta):
	# if game is running and there is a ball move it horizontally with mouse
	if !game_over and ball != null:
		ball.global_position.x = GetMouseXPos()
		if should_drop: # drop if requested
			DropBall()
			should_drop = false
	
	# show countdown and game over
	game_over_label.visible = game_ending
	if game_ending && !game_over:
		game_over_label.text = "%d" % ceil(game_over_timer.time_left)
	if game_over:
		game_over_label.label_settings.font_color = Color("red")
		game_over_label.text = "GAME\nOVER"
		
## Returns global mouse x position clamped between [member GameController.ball_min_x] and [member GameController.ball_max_x]
func GetMouseXPos():
	return clampf(get_global_mouse_position().x, ball_min_x, ball_max_x)

	
func _input(event):
	# also check if ball exists to prevend 2 balls from falling when doubleclicking
	if !game_over && ball != null: 
		if event is InputEventMouseButton:
			if event.button_index == MouseButton.MOUSE_BUTTON_LEFT && !event.pressed: 
				should_drop = true
		if event is InputEventScreenTouch:
			# waits for release to allow for dragging to move the ball
			if !event.pressed: 
				should_drop = true
	elif game_over:
		if event.is_pressed():
			RestartScene()
			
## Reloads current scene
func RestartScene():
	get_tree().reload_current_scene()

## Lets the current ball drop and prepares a new one (after delay)
func DropBall():
	if ball == null:
		return
	ball.Drop()
	ball = null
	await get_tree().create_timer(.5).timeout
	ReadyBall()

## Generates a new [Ball] and saves it to the [member GameController.ball]
## [br][br]
## [Ball] is generated at y = [member GameController.ball_top_offset] and x = [method GameController.GetMouseXPos] [br]
## Level is generated by [method GameController.GetNextLevel]
func ReadyBall():
	var level = GetNextLevel()
	var glob_pos = Vector2(GetMouseXPos(), ball_top_offset)
	var new_ball = CreateBall(glob_pos, level)
	ball = new_ball
	self.add_child.call_deferred(ball)
		
## Returns a new [Ball] of specified [param level] on [param glob_pos] global position
func CreateBall(glob_pos: Vector2, level: int):
	var new_ball: Ball = ball_scene.instantiate()
	new_ball.collision_with_same_ball.connect(_on_same_ball_collision)
	new_ball.level = level
	new_ball.global_position = glob_pos
	return new_ball

## Deletes both balls and adds a new one of higher level in the middle of their original positions
func _on_same_ball_collision(ball1: Ball, ball2: Ball):
	# check if already handled
	if ball1.is_queued_for_deletion() || ball2.is_queued_for_deletion():
		return
	var pos = (ball1.global_position + ball2.global_position) / 2
	var level = (ball1.level + 1)
	ball1.queue_free()
	ball2.queue_free()
	var new_ball = CreateBall(pos, level)
	new_ball.Drop() # make ball interact with environment
	self.add_child.call_deferred(new_ball)

#var lvl = -1
## Returns randomly generated balue beween 0 and 4. 
## The pobability function follow a hyperbolic curve
func GetNextLevel():
	#lvl += 1
	#return (lvl % Ball.level_dict.size())
	
	var rand = randf()
	var level: int = 4
	for i in range(1, 6):
		if rand > 1 / float(i + 1):
			level = i - 1
			break
	return level

## Starts the countdown to end game [br]
## Is called when a body spends too long in [ContainerTopArea]
func _on_timer_to_countdown_timeout() -> void:
	if game_ending:
		return
	game_over_timer.start()
	game_ending = true

## Stops game over countdown [br]
## Called when all bodies leave [ContainerTopArea]
func _on_container_top_area_stop_countdown() -> void:
	if !game_over_timer.is_stopped():
		game_over_timer.stop()
	game_ending = false

## Ends game
## Called on [member GameController.game_over_timer].timeout
func _on_game_over_timer_timeout() -> void:
	game_over = true
